name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: >
      contains(github.event.head_commit.message, 'DEPLOY') &&
      toJson(github.event.head_commit.added) == '[]' &&
      toJson(github.event.head_commit.modified) == '[]' &&
      toJson(github.event.head_commit.removed) == '[]'
    runs-on: self-hosted

    steps:
      - name: Pull, Build, and Restart
        run: |
          cd ~/htdocs/toes.ch
          git pull
          npm ci
          npm run build
          pm2 restart ecosystem.prod.config.cjs
