name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: >
      contains(github.event.head_commit.message, 'DEPLOY')
    # check that the commit message contains 'DEPLOY' and that no files were added, removed, or modified
    runs-on: self-hosted

    steps:
      - name: Pull, Build, and Restart
        run: |
          echo ${GITHUB_EVENT_HEAD_ADDED}
          echo ${GITHUB_EVENT_HEAD_REMOVED}
          echo ${GITHUB_EVENT_HEAD_MODIFIED}
